name: Github Actions

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ${{ matrix.source }} on ${{ matrix.os }} Nuitka ${{ matrix.nuitka-version }}
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13, macos-14]
        nuitka-version: ["1.8.6", "1.9", "2.2.1"]
        source: ["main.py"]

    steps:
      - uses: actions/checkout@v4

      - name: Get Homebrew version
        run: |
          brew --version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          check-latest: true

      - name: Set up Python venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 --version

      - name: Install dependencies
        run: >-
          python3 -m
          pip install
          PySide6-Essentials==6.5.3 nuitka==${{ matrix.nuitka-version }}

      - name: Get Nuitka version
        run: |
          python3 -m nuitka --version

      - name: Get pip freeze
        run: |
          python3 -m pip freeze

      - name: Build with nuitka ${{ matrix.nuitka-version }}
        run: |
          python3 -m nuitka --standalone --plugin-enable=pyside6 --disable-console --assume-yes-for-downloads --macos-create-app-bundle ${{ matrix.source }} --output-dir=nuitka
