name: Github Actions

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ${{ matrix.source }} on ${{ matrix.os }} Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        source: ["main.py", "main-with-qtnetwork.py"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Set up Python venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 --version

      - name: Install dependencies
        run: >-
          python3 -m
          pip install
          "PySide6-Essentials==6.5.3" "nuitka==2.2.1"

      - name: Build with nuitka
        run: |
          python3 -m nuitka --standalone --plugin-enable=pyside6 --disable-console --macos-create-app-bundle ${{ matrix.source }} --output-dir=nuitka
